'use client';

import { MovieData } from '@/types/movie';
import { useState } from 'react';

interface MovieOutputProps {
  data: MovieData;
}

export default function MovieOutput({ data }: MovieOutputProps) {
  const [copied, setCopied] = useState(false);
  const [showShareCaveat, setShowShareCaveat] = useState(false);

  // Format the entire story for sharing/copying
  const getFullStoryText = () =>
    `${data.title}\n\n${data.tagline}\n\nLOG LINE:\n${data.logline}\n\nPLOT:\n${formatPlot(data.plot)}\n\nTRIVIA:\n${data.trivia.join('\n')}\n\nSTARRING: ${data.cast.join(', ')}\nDIRECTED BY: ${data.director}\n\nGenerated by Canonizer 3000`;

  const handleShare = async () => {
    const fullText = getFullStoryText();
    try {
      await navigator.clipboard.writeText(fullText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      // Fallback: do nothing, just proceed to X
    }
    setShowShareCaveat(true);
    const url = window.location.href;
    window.open(
      `https://twitter.com/intent/tweet?text=${encodeURIComponent(fullText)}&url=${encodeURIComponent(url)}`,
      '_blank'
    );
  };

  const handleCopy = async () => {
    const text = getFullStoryText();
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
      alert('Failed to copy to clipboard');
    }
  };

  // Format the plot with better readability
  const formatPlot = (plot: string) => {
    // Remove any existing newlines first
    const cleanedPlot = plot.replace(/\n+/g, ' ').trim();
    
    // Add periods if missing at the end of sentences
    const withProperPunctuation = cleanedPlot.replace(/([.!?])\s+([A-Z])/g, '$1 $2');
    
    // Format as a single paragraph without breaking at arbitrary points
    return withProperPunctuation;
  };

  return (
    <div className="vhs-container">
      <div className="vhs-label">
        <div className="vhs-label-content">
          <h2 className="neon-text">{data.title}</h2>
          <p className="movie-tagline">"{data.tagline}"</p>
        </div>
      </div>
      
      <div className="movie-content">
        <section className="movie-section">
          <div className="section-header">
            <h3 className="movie-section-title">LOG LINE:</h3>
          </div>
          <p className="movie-text">{data.logline}</p>
        </section>

        <section className="movie-section">
          <div className="section-header">
            <h3 className="movie-section-title">PLOT:</h3>
          </div>
          <p className="movie-text whitespace-pre-wrap">{formatPlot(data.plot)}</p>
        </section>

        <section className="movie-section">
          <div className="section-header">
            <h3 className="movie-section-title">TRIVIA:</h3>
          </div>
          <ul className="movie-text trivia-list">
            {data.trivia.map((item, i) => (
              <li key={i} className="trivia-item">
                <span className="trivia-bullet">■</span> {item}
              </li>
            ))}
          </ul>
        </section>

        <div className="movie-credits">
          <section className="movie-section credits-section">
            <div className="section-header">
              <h3 className="movie-section-title">STARRING:</h3>
            </div>
            <p className="movie-text cast-list">
              {data.cast.map((actor, i) => (
                <span key={i} className="cast-member">{actor}</span>
              ))}
            </p>
          </section>

          <section className="movie-section credits-section">
            <div className="section-header">
              <h3 className="movie-section-title">DIRECTED BY:</h3>
            </div>
            <p className="movie-text director">{data.director}</p>
          </section>
        </div>
      </div>

      <div className="mt-8 flex flex-col items-center gap-2">
        <div className="flex justify-center gap-4 w-full">
          <button onClick={handleShare} className="retro-button">
            SHARE TO X
          </button>
          <button onClick={handleCopy} className="retro-button retro-button-accent">
            {copied ? 'COPIED!' : 'COPY ALL'}
          </button>
        </div>
        {showShareCaveat && (
          <div className="text-xs text-neon-orange text-center mt-2 font-orbitron animate-pulse max-w-lg">
            Heads up! Only X (Twitter) Premium accounts can post tweets longer than 280 characters. This story is blockbuster-sized—if you don't have Premium, just paste it manually or share the best bits!
          </div>
        )}
      </div>
    </div>
  );
}
